---

# Populate the Secrets Volume
- name: Create temporary dir for secrets
  command: mktemp -p /tmp -dqt
  register: tempdir

#- debug: var=tempdir

- name: Get the name of the temp directory
  set_fact:
    secrets_tempdir: "{{ tempdir.stdout }}"

- debug: var=secrets_tempdir

- name: Ensure temporary dir exists
  file:
    name: "{{ secrets_tempdir }}"
    state: directory
  register: result

#- debug: var=result.stdout_lines

- name: Populate the temporary dir
  command: python3 {{ playbook_dir }}/../sys/build_secrets_directory.py {{ secrets.name }} {{ secrets.type }} {{secrets.data_dir}} {{ secrets_tempdir }}
  register: result

- debug: var=result.stdout_lines

- name: Copy the data to the container
  command: docker cp {{ secrets_tempdir }}/. {{ secrets_name }}:{{ volumes.secrets.data_dir }}

- name: Ensure temporary dir is removed
  file:
    name: "{{ secrets_tempdir }}"
    state: absent
  register: result
