---

# Get the dangling volumes
- include: roles/ansible_docker_utils/tasks/list_dangling_containers.yml

- debug: var=docker_result

# Remove the dangling volumes
- include: roles/ansible_docker_utils/tasks/remove_image.yml
  vars:
    docker_name: "{{ item }}"
  with_items: "{{ docker_result }}"
  register: result

- debug: var=result.stdout_lines
