---

# Check if the container is running.  If it is, dont' run it
- include: roles/ansible_docker_utils/tasks/is_container_running.yml
  vars:
    docker_name: "{{ containers.sentry_db.name }}"

# Run the container if it isn't running
- include: roles/ansible_docker_utils/tasks/run_container.yml
  vars:
    docker_name: "{{ containers.sentry_db.name }}"
    docker_domain_name: "{{ weave.domain_name }}"
    docker_volumes_from_args: "{{ containers.sentry_db.volumes_from_args }}"
    docker_extra_args: "-d
                        --restart=always"
  register: result
  when: "not {{docker_container_is_running }}"

- debug: var=result.stdout_lines


# Check if postgres is up
- include: roles/utils/tasks/is_postgres_up.yml
  vars:
    utils_name: "{{ containers.sentry_db.name }}"
    utils_retries: "{{ containers.sentry_db.retry_count }}"
    utils_delay: "{{ containers.sentry_db.retry_wait }}"