---

# Check if the container is running.  If it is, dont' run it
- include: roles/ansible_docker_utils/tasks/is_container_running.yml
  vars:
    docker_name: "{{ containers.sentry_worker.name }}"

# Run the container if it isn't running
- include: roles/ansible_docker_utils/tasks/run_container.yml
  vars:
    docker_name: "{{ containers.sentry_worker.name }}"
    docker_domain_name: "{{ weave.domain_name }}"
    docker_volumes_from_args: ""
    docker_extra_args: "-d
                        --restart=always"
  when: "not {{docker_container_is_running }}"
  register: result